//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simansoft.Mpesa.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodigosResposta {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodigosResposta() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simansoft.Mpesa.Core.Resources.CodigosResposta", typeof(CodigosResposta).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request processed successfully.
        /// </summary>
        internal static string INS_0 {
            get {
                return ResourceManager.GetString("INS-0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error.
        /// </summary>
        internal static string INS_1 {
            get {
                return ResourceManager.GetString("INS-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Transaction.
        /// </summary>
        internal static string INS_10 {
            get {
                return ResourceManager.GetString("INS-10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Shortcode Used.
        /// </summary>
        internal static string INS_13 {
            get {
                return ResourceManager.GetString("INS-13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Reference Used.
        /// </summary>
        internal static string INS_14 {
            get {
                return ResourceManager.GetString("INS-14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Amount Used.
        /// </summary>
        internal static string INS_15 {
            get {
                return ResourceManager.GetString("INS-15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to handle the request due to a temporary overloading.
        /// </summary>
        internal static string INS_16 {
            get {
                return ResourceManager.GetString("INS-16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Transaction Reference. Length Should Be Between 1 and 20..
        /// </summary>
        internal static string INS_17 {
            get {
                return ResourceManager.GetString("INS-17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid TransactionID Used.
        /// </summary>
        internal static string INS_18 {
            get {
                return ResourceManager.GetString("INS-18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ThirdPartyReference Used.
        /// </summary>
        internal static string INS_19 {
            get {
                return ResourceManager.GetString("INS-19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid API Key.
        /// </summary>
        internal static string INS_2 {
            get {
                return ResourceManager.GetString("INS-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not All Parameters Provided. Please try again..
        /// </summary>
        internal static string INS_20 {
            get {
                return ResourceManager.GetString("INS-20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiator authentication error..
        /// </summary>
        internal static string INS_2001 {
            get {
                return ResourceManager.GetString("INS-2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver invalid..
        /// </summary>
        internal static string INS_2002 {
            get {
                return ResourceManager.GetString("INS-2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient balance.
        /// </summary>
        internal static string INS_2006 {
            get {
                return ResourceManager.GetString("INS-2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSISDN invalid..
        /// </summary>
        internal static string INS_2051 {
            get {
                return ResourceManager.GetString("INS-2051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language code invalid..
        /// </summary>
        internal static string INS_2057 {
            get {
                return ResourceManager.GetString("INS-2057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter validations failed. Please try again..
        /// </summary>
        internal static string INS_21 {
            get {
                return ResourceManager.GetString("INS-21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Operation Type.
        /// </summary>
        internal static string INS_22 {
            get {
                return ResourceManager.GetString("INS-22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Status. Contact M-Pesa Support.
        /// </summary>
        internal static string INS_23 {
            get {
                return ResourceManager.GetString("INS-23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid InitiatorIdentifier Used.
        /// </summary>
        internal static string INS_24 {
            get {
                return ResourceManager.GetString("INS-24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SecurityCredential Used.
        /// </summary>
        internal static string INS_25 {
            get {
                return ResourceManager.GetString("INS-25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized.
        /// </summary>
        internal static string INS_26 {
            get {
                return ResourceManager.GetString("INS-26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not active.
        /// </summary>
        internal static string INS_4 {
            get {
                return ResourceManager.GetString("INS-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction cancelled by customer.
        /// </summary>
        internal static string INS_5 {
            get {
                return ResourceManager.GetString("INS-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Failed.
        /// </summary>
        internal static string INS_6 {
            get {
                return ResourceManager.GetString("INS-6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request timeout.
        /// </summary>
        internal static string INS_9 {
            get {
                return ResourceManager.GetString("INS-9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Debit Missing.
        /// </summary>
        internal static string INS_993 {
            get {
                return ResourceManager.GetString("INS-993", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Debit Already Exists.
        /// </summary>
        internal static string INS_994 {
            get {
                return ResourceManager.GetString("INS-994", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer&apos;s Profile Has Problems.
        /// </summary>
        internal static string INS_995 {
            get {
                return ResourceManager.GetString("INS-995", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Account Status Not Active.
        /// </summary>
        internal static string INS_996 {
            get {
                return ResourceManager.GetString("INS-996", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linking Transaction Not Found.
        /// </summary>
        internal static string INS_997 {
            get {
                return ResourceManager.GetString("INS-997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Market.
        /// </summary>
        internal static string INS_998 {
            get {
                return ResourceManager.GetString("INS-998", resourceCulture);
            }
        }
    }
}
